// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLNhaTro.Data;

#nullable disable

namespace QLNhaTro.Migrations
{
    [DbContext(typeof(NhaTroDbContext))]
    [Migration("20260417085929_lan1")]
    partial class lan1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLNhaTro.Models.HoaDon", b =>
                {
                    b.Property<int>("HoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoaDonId"));

                    b.Property<string>("AnhThanhToan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HopDongId")
                        .HasColumnType("int");

                    b.Property<int>("SoDienTieuThu")
                        .HasColumnType("int");

                    b.Property<int>("SoNuocTieuThu")
                        .HasColumnType("int");

                    b.Property<DateTime>("Thang")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienDien")
                        .HasColumnType("decimal(18)");

                    b.Property<decimal>("TienNuoc")
                        .HasColumnType("decimal(18)");

                    b.Property<decimal>("TienPhong")
                        .HasColumnType("decimal(18)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18)");

                    b.Property<int>("TrangthaiThanhToan")
                        .HasColumnType("int");

                    b.HasKey("HoaDonId");

                    b.HasIndex("HopDongId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QLNhaTro.Models.HopDong", b =>
                {
                    b.Property<int>("HopDongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HopDongId"));

                    b.Property<int?>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayBatdau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<int>("NguoiThueId")
                        .HasColumnType("int");

                    b.Property<int>("PhongId")
                        .HasColumnType("int");

                    b.Property<decimal>("TienDatCoc")
                        .HasColumnType("decimal(18)");

                    b.HasKey("HopDongId");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("NguoiThueId");

                    b.HasIndex("PhongId");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("QLNhaTro.Models.NguoiThue", b =>
                {
                    b.Property<int>("NguoiThueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiThueId"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiThueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NguoiThueId");

                    b.ToTable("NguoiThues");
                });

            modelBuilder.Entity("QLNhaTro.Models.Phong", b =>
                {
                    b.Property<int>("PhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhongId"));

                    b.Property<float>("DienTich")
                        .HasColumnType("real");

                    b.Property<decimal>("GiaPhong")
                        .HasColumnType("decimal(18)");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhongId");

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("QLNhaTro.Models.HoaDon", b =>
                {
                    b.HasOne("QLNhaTro.Models.HopDong", "HopDong")
                        .WithMany("HoaDons")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("QLNhaTro.Models.HopDong", b =>
                {
                    b.HasOne("QLNhaTro.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonId");

                    b.HasOne("QLNhaTro.Models.NguoiThue", "NguoiThue")
                        .WithMany("HopDongs")
                        .HasForeignKey("NguoiThueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QLNhaTro.Models.Phong", "Phong")
                        .WithMany("HopDongs")
                        .HasForeignKey("PhongId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("NguoiThue");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("ThongBao", b =>
                {
                    b.HasOne("QLNhaTro.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QLNhaTro.Models.HopDong", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QLNhaTro.Models.NguoiThue", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("QLNhaTro.Models.Phong", b =>
                {
                    b.Navigation("HopDongs");
                });
#pragma warning restore 612, 618
        }
    }
}
